# name: Node.js Build
# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master

# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-16.04

#     strategy:
#       matrix:
#         node-version: [12.x]

#     steps:
#       - uses: actions/checkout@master
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}

#       - name: Install dependencies
#         working-directory: ./nest-sample
#         run: yarn install

#       - name: Test
#         working-directory: ./nest-sample
#         run: yarn test

#       - name: Install dependencies
#         working-directory: ./react-typescript-sample
#         run: yarn install

#       - name: Build
#         working-directory: ./react-typescript-sample
#         run: yarn build
